name: Build

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '7.0.x'

    - name: Test
      working-directory: ${{github.workspace}}
      run: dotnet test

  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '7.0.x'

    - name: Run validation
      working-directory: ${{github.workspace}}
      run: dotnet run -c Release --project SeeSharp.Validation

  pack:
    runs-on: ubuntu-latest
    needs: [test, validate]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '7.0.x'

    - name: Pack
      run: dotnet pack -c Release

    - name: Upload .nupkg
      uses: actions/upload-artifact@v2
      with:
        path: ${{github.workspace}}/SeeSharp/bin/**/*.nupkg

    - name: Publish on version change
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: SeeSharp/SeeSharp.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        TAG_COMMIT: false
