name: Build

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'

    # fixes sporadic build fails on Windows (https://github.com/actions/setup-dotnet/issues/155)
    - name: Clean
      run: dotnet clean -c Release && dotnet nuget locals all --clear

    - name: Test
      working-directory: ${{github.workspace}}
      run: dotnet test

  pack:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'

    - name: Pack
      run: dotnet pack -c Release

    - name: Upload .nupkg
      uses: actions/upload-artifact@v2
      with:
        path: ${{github.workspace}}/SeeSharp/bin/**/*.nupkg

    - name: Publish on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: SeeSharp/SeeSharp.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
